# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ploydoo < Formula
  desc "CLI interactivo para montar entornos de desarrollo Odoo"
  homepage "https://github.com/alvarezperezda/ploydoo"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alvarezperezda/ploydoo/releases/download/v1.3.0/ploydoo_darwin_amd64.tar.gz"
      sha256 "28e4a99d85e5719976620a89676e618e8904f18fbe87ec77d80b6430cf3f71bd"

      define_method(:install) do
        bin.install "ploydoo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alvarezperezda/ploydoo/releases/download/v1.3.0/ploydoo_darwin_arm64.tar.gz"
      sha256 "2da1fdc4e058eb62033d3c962cec3df0cee1f59e17c6c0e75ee582baf957af68"

      define_method(:install) do
        bin.install "ploydoo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alvarezperezda/ploydoo/releases/download/v1.3.0/ploydoo_linux_amd64.tar.gz"
      sha256 "0f9d750c39fe96facb2e37487c30faa0563433536894e3a4f8d93879da49e34a"
      define_method(:install) do
        bin.install "ploydoo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alvarezperezda/ploydoo/releases/download/v1.3.0/ploydoo_linux_arm64.tar.gz"
      sha256 "bf853e7fa10867f149a12fccfb6d29d51856bd118b17c8654d2e4f6bd9e9c583"
      define_method(:install) do
        bin.install "ploydoo"
      end
    end
  end

  test do
    system "#{bin}/ploydoo", "--version"
  end
end
