# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ploydoo < Formula
  desc "CLI interactivo para montar entornos de desarrollo Odoo"
  homepage "https://github.com/alvarezperezda/ploydoo"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alvarezperezda/ploydoo/releases/download/v1.2.0/ploydoo_darwin_amd64.tar.gz"
      sha256 "9e0e7326ec91fdd27a42777054ef51ed639d3d5db1e08c5509abb1aec1c14de2"

      define_method(:install) do
        bin.install "ploydoo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alvarezperezda/ploydoo/releases/download/v1.2.0/ploydoo_darwin_arm64.tar.gz"
      sha256 "974a0cd1ddd58348291b0f9f9cd75f983f1c868d520cc18b4999ee1640db6270"

      define_method(:install) do
        bin.install "ploydoo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alvarezperezda/ploydoo/releases/download/v1.2.0/ploydoo_linux_amd64.tar.gz"
      sha256 "ac1945cd0339a1d455739dbb89fef2b6b802b273129882489fe3f415ff959df5"
      define_method(:install) do
        bin.install "ploydoo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alvarezperezda/ploydoo/releases/download/v1.2.0/ploydoo_linux_arm64.tar.gz"
      sha256 "4664b70d84203649fa9be5d9983d88cb5dcb1c09c42a2b8f02090e82e9446c22"
      define_method(:install) do
        bin.install "ploydoo"
      end
    end
  end

  test do
    system "#{bin}/ploydoo", "--version"
  end
end
